# Generated by Django 5.2.4 on 2025-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, default='https://i.imgur.com/7suwDp5.jpeg', null=True),
        ),
    ]
